### ISSUE TITLE
Prefix attribute name with Swagger

### ISSUE THREAD

**Issue by domaindrivendev** [DavidDeSloovere/Swashbuckle.Annotations#7]
Thinking of future devs looking at a WebApi implementation that uses the annotations ...

I think it would be helpful to easily identify attributes that have an effect on the implementation from those that don't. For example, given the following action method ...

    [Authorize(Role = "admin")]
    [LogRequest]
    [ResponseCode(StatusCode = 404, Description = "No calls registered.")]
    public void DoSomething()

It's not immediately clear what the the ResponseCode attribute is actually for. A developer could be forgiven for thinking that, like the other two, it's an action filter that actually effects the behavior of the action.

I think renaming the attribute to [SwaggerResponse] would clarify things a little better while still keeping the name reasonably succint.

**Comment by DavidDeSloovere** [comment]
That makes a lot of sense!
